Eslint prettier structure
huspy/huspy-e2e-api-automation pull request #2
Opened 2023-07-20 12:04 UTC by AlexeyAltunin

2023-07-20 12:25 UTC, harshp92 requested changes

2023-07-20 12:25 UTC, harshp92 commented on yarn.lock
can we add the lock file to gitignore?

2023-07-20 12:31 UTC, harshp92 approved these changes

2023-07-24 11:09 UTC, alexAtHuspy approved these changes

2023-07-24 11:10 UTC, alexAtHuspy approved these changes

2023-07-24 11:10 UTC, alexAtHuspy commented on .gitignore
> +yarn.lock
need an empty line

2023-07-24 11:46 UTC, AlexeyAltunin commented on .gitignore
> +yarn.lock
for next PRs

2023-07-24 12:27 UTC, alexAtHuspy approved these changes

2023-07-24 12:55 UTC, merged